######################################################################
##
## Filename: sub_byte_trans.udo
## Created on: Tue Apr 23 11:34:28 Paris, Madrid (heure d’été) 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
